### ISSUE TITLE
Create a DiscordBot as initial version of interface to interact with BlameAI model

### ISSUE THREAD

**Issue by sergynekko** [aifoundry-org/blame-ai-discord-bot#1]
- [x]  Bot setup
- [x]  Empty bot structure
- [x] This calls a no-op from the blame.ai perspective until we have data fetching done and returns an empty message

**Comment by antonekko** [comment]
[UPD] Bot setup
Basic setup is done, but there will be further changes later - from time to time, to enable needed permission scopes.

Details:
I've setup a new Team on Discord Developer Portal - called AIFoundry.org.
I've created 2 applications (bots), "production" one (called Blame.AI) and "development/pilot" one (called [DEV] Blame.AI).
So far I've made them both private, yet already added into the description that there is no affiliation with GitHub, just to be safe.


![Image](https://github.com/user-attachments/assets/f8b7c39a-6ebf-46b9-b389-957c00095713)



![Image](https://github.com/user-attachments/assets/82bb41b7-19e9-466e-b70e-2719c8af4184)

If anyone wants to be part of mentioned dev team on discord developer portal - please ping me.

**Comment by antonekko** [comment]
[UPD] GH logo was a bad choice, I updated it with new one:


![Image](https://github.com/user-attachments/assets/a2ec9e56-d74d-4698-b316-f371b3c9ce77)



![Image](https://github.com/user-attachments/assets/ca49de3f-bd75-4732-8bf7-1e2a6a4767ae)

**Comment by antonekko** [comment]
Specific description of capabilities is in https://github.com/aifoundry-org/blame-ai-discord-bot/blob/main/README.md
